Add Branch Rules
YubicoLabs/gitbark pull request #29
Opened 2023-11-02 15:42 UTC by dainnilsson

2023-11-02 16:18 UTC, elibon99 commented on gitbark/cli/__main__.py
> +        raise e
I'm guessing this should be removed?f

2023-11-02 16:19 UTC, elibon99 commented on gitbark/cli/__main__.py
> +            f"The bootstrap commit ({root_commit.hash.hex()}) of the branch_rules "
"branch_rules" should be changed to "bark_rules". This is not due to  theses changes (it has been like this for a while), but would be nice to use a constant instead.

2023-11-02 16:20 UTC, elibon99 requested changes

2023-11-02 16:20 UTC, elibon99 commented on gitbark/cli/__main__.py
> +        raise e
I'm guessing this should be removed?

2023-11-02 18:17 UTC, dainnilsson commented on gitbark/cli/__main__.py
> +        raise e
Yeah. We should probably improve the standard error output here to be more descriptive.

2023-11-02 18:18 UTC, elibon99 approved these changes

2023-11-03 09:27 UTC, merged

2023-11-03 09:28 UTC, elibon99 approved these changes